### ISSUE TITLE
Publish imagemounter dependency?

### ISSUE THREAD

**Issue by mehaase** [mitre/thumbtack#104]
The dependency on the imagemount git repo means that every build environment that transitively depends on thumbtack needs git installed just to install this package. Can we look into publishing this package? I recognize that it's a fork and somebody else owns the name on PyPI, but we have a few options:

* Ask to merge our changes back into original fork.
* Contact PyPI and ask to have the name transferred to us.
* Publish the package under a new name.

**Comment by jondricek** [comment]
I just reached out to the upstream repo owner here in this issue to get the discussion started a bit more.

https://github.com/ralphje/imagemounter/issues/39

**Comment by jondricek** [comment]
Looks like he is willing to work with us on merging in our changes/uploading things to PyPI. That said, we should take some time this week to brush up on what our commit over in mitre/imagemounter was about, see why we're 40 commits behind, etc. before making any pull requests.

@agibbons27 - is this something you could look into?
